include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_internal_member: error

linter:
  rules:
    avoid_catches_without_on_clauses: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    prefer_final_locals: true
    unawaited_futures: true
