import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
const result = await build({
  entryPoints: [
    new URL("../src/browser/admin_entry.ts", import.meta.url).pathname,
  ],
  bundle: true,
  write: false,
  minify: true,
  platform: "browser",
  target: "es2022",
  format: "iife",
});
await writeFile(
  new URL("../src/http/admin_browser_bundle.ts", import.meta.url),
  "// Generated by scripts/build-admin.mjs; do not edit.\n// prettier-ignore\nexport const adminBrowserScript = " +
    JSON.stringify(result.outputFiles[0].text) +
    ";\n",
);
